### ISSUE TITLE
feat: slo burn rate alerting policies

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-slo#88]
it would be great if the module could accept pairs of lookback period + burnrate threshold, and generate alerting policies, with an example/default of setting up the recommended starting point fast (60 minutes + 10x) + slow (24h + 2x) burn rate alerts.

**Comment by ocervell** [comment]
Hi @naseemkullah , this is not possible in the Service Monitoring API currently, but it might be possible to implement using the slo-generator. Could you re-open this issue in the corresponding repo (https://github.com/google/slo-generator) ? Thanks :)
